// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/proto/ca/server.proto

package ca

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("grpc/proto/ca/server.proto", fileDescriptor_e7149eeb85e0e507) }

var fileDescriptor_e7149eeb85e0e507 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xb1, 0x4a, 0xc4, 0x40,
	0x10, 0x86, 0xc3, 0x15, 0x22, 0x2b, 0x8a, 0x37, 0xa7, 0x22, 0x5b, 0x06, 0x2c, 0xdd, 0x80, 0x16,
	0x36, 0x16, 0x72, 0x03, 0x5a, 0x28, 0x28, 0xda, 0xd9, 0x4d, 0xc6, 0xb9, 0xb8, 0x70, 0x24, 0x71,
	0xb2, 0x0a, 0xf7, 0x0c, 0xbe, 0xb4, 0x24, 0x71, 0xa3, 0x0b, 0xd7, 0xed, 0x7c, 0xff, 0x7e, 0x33,
	0xf0, 0x1b, 0x5b, 0x69, 0xcb, 0x45, 0xab, 0x4d, 0x68, 0x0a, 0xa6, 0xa2, 0x13, 0xfd, 0x12, 0x75,
	0xc3, 0x0c, 0x33, 0x26, 0x7b, 0x9a, 0xe6, 0x2c, 0x1a, 0xc6, 0xf4, 0xe2, 0x7b, 0x66, 0x76, 0xef,
	0xa4, 0x16, 0xa5, 0x20, 0x70, 0x65, 0x0e, 0xe2, 0x1b, 0x75, 0xd3, 0x86, 0x06, 0x0e, 0x1d, 0x93,
	0x7b, 0x96, 0x8f, 0x7b, 0xd9, 0x60, 0x53, 0xaf, 0x7c, 0x65, 0xe7, 0x23, 0xe9, 0xda, 0x09, 0xe5,
	0x19, 0xdc, 0x98, 0x79, 0x14, 0x1f, 0x84, 0xaa, 0x4f, 0x41, 0x0d, 0xb0, 0xf8, 0x75, 0x51, 0x65,
	0xe2, 0xf6, 0x28, 0xea, 0xff, 0x69, 0x9e, 0xc1, 0xb5, 0x59, 0xc4, 0x0d, 0x8f, 0x5a, 0xe1, 0xbb,
	0x5f, 0xbf, 0x61, 0xa7, 0xd3, 0xfd, 0xf1, 0x37, 0x76, 0xfa, 0x77, 0x7f, 0x42, 0x79, 0x06, 0xb7,
	0x5b, 0x6c, 0x0d, 0x70, 0x9c, 0xd8, 0x31, 0xb1, 0x27, 0xe9, 0x8a, 0xc8, 0xf3, 0x6c, 0x89, 0xe6,
	0x8c, 0x6b, 0x47, 0xa5, 0xa8, 0x67, 0xb7, 0xa2, 0x52, 0x3d, 0x9f, 0xf3, 0xda, 0x4b, 0x1d, 0x5c,
	0xdf, 0xe0, 0xd8, 0x99, 0x63, 0x5a, 0xee, 0xbd, 0x0c, 0x15, 0x3f, 0xf5, 0xf3, 0xeb, 0x7e, 0xd2,
	0x6e, 0xb9, 0x33, 0xbc, 0x2e, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x2c, 0xc7, 0x0f, 0x95,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GenerateClient is the client API for Generate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GenerateClient interface {
	// 生成密钥对
	GenerateCrypto(ctx context.Context, in *ReqKeyConfig, opts ...grpc.CallOption) (*RespKeyConfig, error)
	// 生成联盟根证书
	GenerateLeagueCrt(ctx context.Context, in *ReqCreateLeague, opts ...grpc.CallOption) (*RespCreateLeague, error)
	// 生成组织下子节点/用户CA请求证书文件
	GenerateOrgChildCsr(ctx context.Context, in *ReqCreateCsr, opts ...grpc.CallOption) (*RespCreateCsr, error)
	// 生成组织下子节点/用户证书
	GenerateOrgChildCrt(ctx context.Context, in *ReqCreateOrgChild, opts ...grpc.CallOption) (*RespCreateOrgChild, error)
}

type generateClient struct {
	cc *grpc.ClientConn
}

func NewGenerateClient(cc *grpc.ClientConn) GenerateClient {
	return &generateClient{cc}
}

func (c *generateClient) GenerateCrypto(ctx context.Context, in *ReqKeyConfig, opts ...grpc.CallOption) (*RespKeyConfig, error) {
	out := new(RespKeyConfig)
	err := c.cc.Invoke(ctx, "/ca.Generate/GenerateCrypto", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *generateClient) GenerateLeagueCrt(ctx context.Context, in *ReqCreateLeague, opts ...grpc.CallOption) (*RespCreateLeague, error) {
	out := new(RespCreateLeague)
	err := c.cc.Invoke(ctx, "/ca.Generate/GenerateLeagueCrt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *generateClient) GenerateOrgChildCsr(ctx context.Context, in *ReqCreateCsr, opts ...grpc.CallOption) (*RespCreateCsr, error) {
	out := new(RespCreateCsr)
	err := c.cc.Invoke(ctx, "/ca.Generate/GenerateOrgChildCsr", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *generateClient) GenerateOrgChildCrt(ctx context.Context, in *ReqCreateOrgChild, opts ...grpc.CallOption) (*RespCreateOrgChild, error) {
	out := new(RespCreateOrgChild)
	err := c.cc.Invoke(ctx, "/ca.Generate/GenerateOrgChildCrt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GenerateServer is the server API for Generate service.
type GenerateServer interface {
	// 生成密钥对
	GenerateCrypto(context.Context, *ReqKeyConfig) (*RespKeyConfig, error)
	// 生成联盟根证书
	GenerateLeagueCrt(context.Context, *ReqCreateLeague) (*RespCreateLeague, error)
	// 生成组织下子节点/用户CA请求证书文件
	GenerateOrgChildCsr(context.Context, *ReqCreateCsr) (*RespCreateCsr, error)
	// 生成组织下子节点/用户证书
	GenerateOrgChildCrt(context.Context, *ReqCreateOrgChild) (*RespCreateOrgChild, error)
}

func RegisterGenerateServer(s *grpc.Server, srv GenerateServer) {
	s.RegisterService(&_Generate_serviceDesc, srv)
}

func _Generate_GenerateCrypto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqKeyConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenerateServer).GenerateCrypto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ca.Generate/GenerateCrypto",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenerateServer).GenerateCrypto(ctx, req.(*ReqKeyConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _Generate_GenerateLeagueCrt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqCreateLeague)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenerateServer).GenerateLeagueCrt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ca.Generate/GenerateLeagueCrt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenerateServer).GenerateLeagueCrt(ctx, req.(*ReqCreateLeague))
	}
	return interceptor(ctx, in, info, handler)
}

func _Generate_GenerateOrgChildCsr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqCreateCsr)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenerateServer).GenerateOrgChildCsr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ca.Generate/GenerateOrgChildCsr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenerateServer).GenerateOrgChildCsr(ctx, req.(*ReqCreateCsr))
	}
	return interceptor(ctx, in, info, handler)
}

func _Generate_GenerateOrgChildCrt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqCreateOrgChild)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenerateServer).GenerateOrgChildCrt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ca.Generate/GenerateOrgChildCrt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenerateServer).GenerateOrgChildCrt(ctx, req.(*ReqCreateOrgChild))
	}
	return interceptor(ctx, in, info, handler)
}

var _Generate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ca.Generate",
	HandlerType: (*GenerateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateCrypto",
			Handler:    _Generate_GenerateCrypto_Handler,
		},
		{
			MethodName: "GenerateLeagueCrt",
			Handler:    _Generate_GenerateLeagueCrt_Handler,
		},
		{
			MethodName: "GenerateOrgChildCsr",
			Handler:    _Generate_GenerateOrgChildCsr_Handler,
		},
		{
			MethodName: "GenerateOrgChildCrt",
			Handler:    _Generate_GenerateOrgChildCrt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/proto/ca/server.proto",
}
