version: 1.4.0
port: 7054
debug: false
crlsizelimit: 512000
tls:
  enabled: true
  certfile: tlsca.cert
  keyfile: tlsca.key
  clientauth:
    type: noclientcert
    certfiles:
ca:
  name: rootCA
  keyfile: ca.key
  certfile: ca.cert
crl:
  expiry: 24h
registry:
  maxenrollments: -1
  identities:
    - name: admin
      pass: adminpw
      type: client
      affiliation: ""
      attrs:
        hf.Registrar.Roles: "*"
        hf.Registrar.DelegateRoles: "*"
        hf.Revoker: true
        hf.IntermediateCA: true
        hf.GenCRL: true
        hf.Registrar.Attributes: "*"
        hf.AffiliationMgr: true
signing:
  default:
    usage:
      - digital signature
    expiry: 8760h
  profiles:
    ca:
      usage:
        - cert sign
        - crl sign
      expiry: 43800h
      caconstraint:
        isca: true
        maxpathlen: 0
    tls:
      usage:
        - signing
        - key encipherment
        - server auth
        - client auth
        - key agreement
      expiry: 8760h
csr:
  cn: xxchain
  keyrequest:
    algo: ecdsa
    size: 256
  names:
    - C: CN
      ST: Beijing
      L: Beijing
      O: Viewhigh
      OU: Blockchain
  hosts:
    - localhost
    - 127.0.0.1
  ca:
    expiry: 175200h
    pathlength: 2
idemix:
  rhpoolsize: 1000
  nonceexpiration: 15s
  noncesweepinterval: 15m
bccsp:
  default: SW
  sw:
    hash: SHA2
    security: 256
    filekeystore:
      keystore: msp/keystore
cfg:
  identities:
    passwordattempts: 10